### ISSUE TITLE
occ upgrade when nextcloud config exists

### ISSUE THREAD

**Issue by in0rdr** [adfinis-sygroup/base4kids2-ansible#8]
https://github.com/adfinis-sygroup/base4kids2-ansible/blob/8890e1c4519e30275a0d08e2e8b81e9df403b5dc/roles/nextcloud/tasks/configuration.yml#L50

Also, is there another way to check for an existing Nextcloud instead of using `nextcloud_config_file.stat.exists`? Maybe `occ status`:
```
occ status
  - installed: true
  - version: 15.0.0.10
  - versionstring: 15.0.0
  - edition: 
```
